In [1]:
print("hello");

hello

In [2]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta


print("Data Generating ......");
# Settings
num_rows = 25000
start_date = datetime(2022, 1, 1)
end_date = datetime(2025, 12, 31)

# Geographic Mapping
geo_data = {
    "Pakistan": {
        "Punjab": [("Lahore", 31.5204, 74.3587), ("Faisalabad", 31.4504, 73.1350), ("Multan", 30.1575, 71.5249)],
        "Sindh": [("Karachi", 24.8607, 67.0011), ("Hyderabad", 25.3960, 68.3578)],
        "ICT": [("Islamabad", 33.6844, 73.0479)]
    },
    "USA": {
        "California": [("Los Angeles", 34.0522, -118.2437), ("San Francisco", 37.7749, -122.4194)],
        "New York": [("New York City", 40.7128, -74.0060)],
        "Texas": [("Houston", 29.7604, -95.3698)]
    },
    "Germany": {
        "Bavaria": [("Munich", 48.1351, 11.5820)],
        "Berlin": [("Berlin", 52.5200, 13.4050)],
        "Hesse": [("Frankfurt", 50.1109, 8.6821)]
    },
    "India": {
        "Maharashtra": [("Mumbai", 19.0760, 72.8777)],
        "Delhi": [("New Delhi", 28.6139, 77.2090)],
        "Karnataka": [("Bangalore", 12.9716, 77.5946)]
    },
    "United Kingdom": {
        "England": [("London", 51.5074, -0.1278), ("Manchester", 53.4808, -2.2426)]
    },
    "Australia": {
        "NSW": [("Sydney", -33.8688, 151.2093)],
        "Victoria": [("Melbourne", -37.8136, 144.9631)]
    },
    "Canada": {
        "Ontario": [("Toronto", 43.6532, -79.3832)],
        "Quebec": [("Montreal", 45.5017, -73.5673)]
    }
}

# Product Data
products = {
    "Bikes": {
        "Mountain Bikes": [("Mountain-100 Black", "BK-M18B-42", 2500), ("Mountain-500 Silver", "BK-M50S-48", 3200)],
        "Road Bikes": [("Road-150 Red", "BK-R15R-62", 1500), ("Road-650 Black", "BK-R65B-52", 4000)]
    },
    "Accessories": {
        "Helmets": [("Sport-100 Helmet Red", "HL-U509-R", 35), ("Sport-100 Helmet Black", "HL-U509-B", 35)],
        "Tires": [("Patch Kit/8 Patches", "TI-R092", 5), ("Mountain Tire Tube", "TI-M048", 10)]
    },
    "Clothing": {
        "Jerseys": [("Long-Sleeve Logo Jersey S", "CL-J01-S", 50), ("Short-Sleeve Classic M", "CL-J05-M", 45)],
        "Shorts": [("Women's Mountain Shorts L", "CL-S02-L", 70)]
    },
    "Components": {
        "Drivetrain": [("LL Crankset", "CO-C11", 150), ("HL Mountain Pedal", "CO-P22", 80)]
    }
}

countries = list(geo_data.keys())
segments = ["Consumer", "Corporate", "Small Business"]
channels = ["Online", "Offline/Store"]
reps = ["Ahmed Khan", "John Smith", "Maria Garcia", "Wei Chen", "Sarah Jenkins", "Fatima Ali"]
promos = ["SUMMER25", "WINTER_OFFER", "NO_PROMO", "BLACKFRIDAY", "EID_SPECIAL"]

# Generation
data = []

for i in range(num_rows):
    # Create a list of 25,000 unique timestamps by adding random seconds
# This ensures no two rows are exactly the sam
    total_seconds = int((end_date - start_date).total_seconds())
    random_seconds = random.sample(range(total_seconds), num_rows)
    random_seconds.sort() # Optional: keeps the CSV somewhat chronological

for i in range(num_rows):
    # Generate a unique date + time
    date = start_date + timedelta(seconds=random_seconds[i])
    
    # Seasonality Factor (unchanged logic, but now applied to unique dates)
    season_mult = 1.0
    if date.month == 12: season_mult = 1.4
    if date.month == 7: season_mult = 1.2
    if date.weekday() >= 5: season_mult *= 1.1
    
    # Rest of your logic...
    # Use date.strftime("%Y-%m-%d %H:%M:%S") for the CSV output

    
    # # Date logic
    # date = start_date + timedelta(days=random.randint(0, (end_date - start_date).days))
    
    # # Seasonality Factor (Dec/July/weekends)
    # season_mult = 1.0
    # if date.month == 12: season_mult = 1.4
    # if date.month == 7: season_mult = 1.2
    # if date.weekday() >= 5: season_mult *= 1.1
    
    
    # Hierarchy Logic
    country = "Pakistan" if random.random() < 0.3 else random.choice(countries) # Weighting Pakistan as requested
    region = random.choice(list(geo_data[country].keys()))
    city_info = random.choice(geo_data[country][region])
    city, lat, lon = city_info
    
    cat = random.choice(list(products.keys()))
    subcat = random.choice(list(products[cat].keys()))
    prod_info = random.choice(products[cat][subcat])
    prod_name, prod_id, base_price = prod_info
    
    # Measures
    qty = random.randint(1, 10) if cat == "Bikes" else random.randint(1, 50)
    unit_price = base_price * random.uniform(0.9, 1.1)
    revenue = (unit_price * qty) * season_mult
    
    # Pakistan Specific Pricing (Scaling PKR vs USD internally for variety)
    if country == "Pakistan": revenue *= 150 # Simulated PKR values
    
    discount_pct = random.uniform(0, 0.25) if random.random() > 0.7 else 0
    discount_amt = revenue * discount_pct
    cogs = revenue * random.uniform(0.4, 0.7)
    gross_profit = revenue - discount_amt - cogs
    returns = random.randint(1, 3) if random.random() > 0.96 else 0
    net_revenue = revenue - discount_amt - (returns * unit_price)
    
    data.append([
        date.strftime("%Y-%m-%d"), country, region, city, lat, lon,
        cat, subcat, prod_name, prod_id,
        random.choice(segments), f"CUST-{random.randint(1000, 9999)}", f"Customer_{i%500}",
        random.choice(channels), random.choice(reps), 
        "NO_PROMO" if discount_amt == 0 else random.choice(promos),
        round(revenue, 2), qty, round(unit_price, 2), round(discount_amt, 2),
        round(cogs, 2), round(gross_profit, 2), returns, round(net_revenue, 2)
    ])

# Create DataFrame
columns = [
    "Date", "Country", "Region", "City", "Latitude", "Longitude",
    "Product_Category", "Product_Sub_Category", "Product_Name", "Product_ID",
    "Customer_Segment", "Customer_ID", "Customer_Name",
    "Sales_Channel", "Sales_Representative", "Promotion",
    "Sales_Revenue", "Quantity_Sold", "Unit_Price", "Discount_Amount",
    "Cost_of_Goods_Sold", "Gross_Profit", "Returns_Units", "Net_Revenue"
]

df = pd.DataFrame(data, columns=columns)
df.to_csv("01Global_Retail_Sales_Analytics_Dataset.csv", index=False)
print("DONE");

Data Generating ......
DONE

In [3]:
df.head(5)

,Date,Country,Region,City,Latitude,Longitude,Product_Category,Product_Sub_Category,Product_Name,Product_ID,...,Sales_Representative,Promotion,Sales_Revenue,Quantity_Sold,Unit_Price,Discount_Amount,Cost_of_Goods_Sold,Gross_Profit,Returns_Units,Net_Revenue
0,2022-01-01,Pakistan,ICT,Islamabad,33.6844,73.0479,Accessories,Tires,Mountain Tire Tube,TI-M048,...,Maria Garcia,NO_PROMO,76256.80,45,10.27,0.00,45154.29,31102.51,0,76256.80
1,2022-01-01,Pakistan,Sindh,Hyderabad,25.3960,68.3578,Components,Drivetrain,HL Mountain Pedal,CO-P22,...,Sarah Jenkins,BLACKFRIDAY,391468.39,32,74.14,7279.53,248675.55,135513.31,0,384188.86
2,2022-01-01,Pakistan,Punjab,Multan,30.1575,71.5249,Bikes,Mountain Bikes,Mountain-100 Black,BK-M18B-42,...,John Smith,NO_PROMO,4014807.29,10,2433.22,0.00,2069318.38,1945488.91,0,4014807.29
3,2022-01-01,United Kingdom,England,London,51.5074,-0.1278,Clothing,Shorts,Women's Mountain Shorts L,CL-S02-L,...,Sarah Jenkins,SUMMER25,2457.14,34,65.70,401.42,1270.66,785.06,0,2055.72
4,2022-01-01,Pakistan,Sindh,Karachi,24.8607,67.0011,Bikes,Mountain Bikes,Mountain-500 Silver,BK-M50S-48,...,Ahmed Khan,NO_PROMO,1120615.88,2,3395.81,0.00,735335.30,385280.58,0,1120615.88

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  25000 non-null  object
 1   Country               25000 non-null  object
 2   Region                25000 non-null  object
 3   City                  25000 non-null  object
 4   Latitude              25000 non-null  float64
 5   Longitude             25000 non-null  float64
 6   Product_Category      25000 non-null  object
 7   Product_Sub_Category  25000 non-null  object
 8   Product_Name          25000 non-null  object
 9   Product_ID            25000 non-null  object
 10  Customer_Segment      25000 non-null  object
 11  Customer_ID           25000 non-null  object
 12  Customer_Name         25000 non-null  object
 13  Sales_Channel         25000 non-null  object
 14  Sales_Representative  25000 non-null  object
 15  Promotion             25000 non-null  object
 16  Sales_Revenue         25000 non-null  float64
 17  Quantity_Sold         25000 non-null  int64
 18  Unit_Price            25000 non-null  float64
 19  Discount_Amount       25000 non-null  float64
 20  Cost_of_Goods_Sold    25000 non-null  float64
 21  Gross_Profit          25000 non-null  float64
 22  Returns_Units         25000 non-null  int64
 23  Net_Revenue           25000 non-null  float64
dtypes: float64(8), int64(2), object(14)
memory usage: 4.6+ MB

In [4]:
df.tail()

,Date,Country,Region,City,Latitude,Longitude,Product_Category,Product_Sub_Category,Product_Name,Product_ID,...,Sales_Representative,Promotion,Sales_Revenue,Quantity_Sold,Unit_Price,Discount_Amount,Cost_of_Goods_Sold,Gross_Profit,Returns_Units,Net_Revenue
24995,2025-12-30,Pakistan,Punjab,Faisalabad,31.4504,73.1350,Clothing,Shorts,Women's Mountain Shorts L,CL-S02-L,...,Maria Garcia,NO_PROMO,567037.73,40,67.50,0.00,254974.16,312063.57,0,567037.73
24996,2025-12-30,Australia,Victoria,Melbourne,-37.8136,144.9631,Accessories,Helmets,Sport-100 Helmet Black,HL-U509-B,...,John Smith,NO_PROMO,863.84,19,32.48,0.00,350.07,513.77,0,863.84
24997,2025-12-30,USA,California,Los Angeles,34.0522,-118.2437,Bikes,Road Bikes,Road-650 Black,BK-R65B-52,...,Sarah Jenkins,NO_PROMO,36975.12,7,3772.97,0.00,23989.98,12985.14,0,36975.12
24998,2025-12-30,Germany,Bavaria,Munich,48.1351,11.5820,Clothing,Jerseys,Long-Sleeve Logo Jersey S,CL-J01-S,...,John Smith,BLACKFRIDAY,691.45,9,54.88,114.18,290.22,287.05,0,577.28
24999,2025-12-30,Germany,Berlin,Berlin,52.5200,13.4050,Accessories,Tires,Patch Kit/8 Patches,TI-R092,...,Sarah Jenkins,EID_SPECIAL,275.32,41,4.80,33.67,167.37,74.27,0,241.64

In [12]:
# Final  Dataset ..........

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

print("Data Generating ......")

# Settings
num_rows = 25000
start_date = datetime(2019, 1, 1, 0, 0, 0)
end_date   = datetime(2026, 4, 17, 23, 59, 59)

# ── UNIQUE TIMESTAMPS (no repetition, with time) ──────────────────────────────
total_seconds = int((end_date - start_date).total_seconds())  # ~232 million secs
assert total_seconds >= num_rows, "Date range too small for unique timestamps!"

unique_offsets = random.sample(range(total_seconds), num_rows)
unique_offsets.sort()   # chronological order
unique_dates  = [start_date + timedelta(seconds=s) for s in unique_offsets]
# ──────────────────────────────────────────────────────────────────────────────

# Geographic Mapping
geo_data = {
    "Pakistan": {
        "Punjab": [("Lahore", 31.5204, 74.3587), ("Faisalabad", 31.4504, 73.1350), ("Multan", 30.1575, 71.5249)],
        "Sindh": [("Karachi", 24.8607, 67.0011), ("Hyderabad", 25.3960, 68.3578)],
        "ICT": [("Islamabad", 33.6844, 73.0479)]
    },
    "USA": {
        "California": [("Los Angeles", 34.0522, -118.2437), ("San Francisco", 37.7749, -122.4194)],
        "New York": [("New York City", 40.7128, -74.0060)],
        "Texas": [("Houston", 29.7604, -95.3698)]
    },
    "Germany": {
        "Bavaria": [("Munich", 48.1351, 11.5820)],
        "Berlin": [("Berlin", 52.5200, 13.4050)],
        "Hesse": [("Frankfurt", 50.1109, 8.6821)]
    },
    "India": {
        "Maharashtra": [("Mumbai", 19.0760, 72.8777)],
        "Delhi": [("New Delhi", 28.6139, 77.2090)],
        "Karnataka": [("Bangalore", 12.9716, 77.5946)]
    },
    "United Kingdom": {
        "England": [("London", 51.5074, -0.1278), ("Manchester", 53.4808, -2.2426)]
    },
    "Australia": {
        "NSW": [("Sydney", -33.8688, 151.2093)],
        "Victoria": [("Melbourne", -37.8136, 144.9631)]
    },
    "Canada": {
        "Ontario": [("Toronto", 43.6532, -79.3832)],
        "Quebec": [("Montreal", 45.5017, -73.5673)]
    }
}

# Product Data
products = {
    "Bikes": {
        "Mountain Bikes": [("Mountain-100 Black", "BK-M18B-42", 2500), ("Mountain-500 Silver", "BK-M50S-48", 3200)],
        "Road Bikes":     [("Road-150 Red",       "BK-R15R-62", 1500), ("Road-650 Black",     "BK-R65B-52", 4000)]
    },
    "Accessories": {
        "Helmets": [("Sport-100 Helmet Red",  "HL-U509-R", 35), ("Sport-100 Helmet Black", "HL-U509-B", 35)],
        "Tires":   [("Patch Kit/8 Patches",   "TI-R092",    5), ("Mountain Tire Tube",     "TI-M048",   10)]
    },
    "Clothing": {
        "Jerseys": [("Long-Sleeve Logo Jersey S", "CL-J01-S", 50), ("Short-Sleeve Classic M", "CL-J05-M", 45)],
        "Shorts":  [("Women's Mountain Shorts L", "CL-S02-L", 70)]
    },
    "Components": {
        "Drivetrain": [("LL Crankset", "CO-C11", 150), ("HL Mountain Pedal", "CO-P22", 80)]
    }
}

countries = list(geo_data.keys())
segments  = ["Consumer", "Corporate", "Small Business"]
channels  = ["Online", "Offline/Store"]
reps      = ["Ahmed Khan", "John Smith", "Maria Garcia", "Wei Chen", "Sarah Jenkins", "Fatima Ali"]
promos    = ["SUMMER25", "WINTER_OFFER", "NO_PROMO", "BLACKFRIDAY", "EID_SPECIAL"]

# ── Row Generation ─────────────────────────────────────────────────────────────
data = []

for i in range(num_rows):
    date = unique_dates[i]          # guaranteed unique datetime with time component

    # Seasonality factor
    season_mult = 1.0
    if date.month == 12:        season_mult  = 1.4
    if date.month == 7:         season_mult  = 1.2
    if date.weekday() >= 5:     season_mult *= 1.1

    # Geography
    country   = "Pakistan" if random.random() < 0.3 else random.choice(countries)
    region    = random.choice(list(geo_data[country].keys()))
    city, lat, lon = random.choice(geo_data[country][region])

    # Product
    cat       = random.choice(list(products.keys()))
    subcat    = random.choice(list(products[cat].keys()))
    prod_name, prod_id, base_price = random.choice(products[cat][subcat])

    # Measures
    qty        = random.randint(1, 10)  if cat == "Bikes" else random.randint(1, 50)
    unit_price = base_price * random.uniform(0.9, 1.1)
    revenue    = (unit_price * qty) * season_mult
    if country == "Pakistan":
        revenue *= 150                  # simulated PKR values

    discount_pct  = random.uniform(0, 0.25) if random.random() > 0.7 else 0
    discount_amt  = revenue * discount_pct
    cogs          = revenue * random.uniform(0.4, 0.7)
    gross_profit  = revenue - discount_amt - cogs
    returns       = random.randint(1, 3) if random.random() > 0.96 else 0
    net_revenue   = revenue - discount_amt - (returns * unit_price)

    data.append([
        date.strftime("%Y-%m-%d %H:%M:%S"),   # ← full datetime, unique per row
        country, region, city, lat, lon,
        cat, subcat, prod_name, prod_id,
        random.choice(segments),
        f"CUST-{random.randint(1000, 9999)}",
        f"Customer_{i % 500}",
        random.choice(channels),
        random.choice(reps),
        "NO_PROMO" if discount_amt == 0 else random.choice(promos),
        round(revenue, 2), qty, round(unit_price, 2), round(discount_amt, 2),
        round(cogs, 2), round(gross_profit, 2), returns, round(net_revenue, 2)
    ])

# ── Export ─────────────────────────────────────────────────────────────────────
columns = [
    "Date", "Country", "Region", "City", "Latitude", "Longitude",
    "Product_Category", "Product_Sub_Category", "Product_Name", "Product_ID",
    "Customer_Segment", "Customer_ID", "Customer_Name",
    "Sales_Channel", "Sales_Representative", "Promotion",
    "Sales_Revenue", "Quantity_Sold", "Unit_Price", "Discount_Amount",
    "Cost_of_Goods_Sold", "Gross_Profit", "Returns_Units", "Net_Revenue"
]

dfV2 = pd.DataFrame(data, columns=columns)
dfV2.to_csv("V2_Global_Retail_Sales_Analytics_Dataset.csv", index=False)
print("DONE — Rows:", len(df), "| Unique dates:", df['Date'].nunique())

Data Generating ......
DONE — Rows: 25000 | Unique dates: 25000

In [13]:
dfV2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date                  25000 non-null  object
 1   Country               25000 non-null  object
 2   Region                25000 non-null  object
 3   City                  25000 non-null  object
 4   Latitude              25000 non-null  float64
 5   Longitude             25000 non-null  float64
 6   Product_Category      25000 non-null  object
 7   Product_Sub_Category  25000 non-null  object
 8   Product_Name          25000 non-null  object
 9   Product_ID            25000 non-null  object
 10  Customer_Segment      25000 non-null  object
 11  Customer_ID           25000 non-null  object
 12  Customer_Name         25000 non-null  object
 13  Sales_Channel         25000 non-null  object
 14  Sales_Representative  25000 non-null  object
 15  Promotion             25000 non-null  object
 16  Sales_Revenue         25000 non-null  float64
 17  Quantity_Sold         25000 non-null  int64
 18  Unit_Price            25000 non-null  float64
 19  Discount_Amount       25000 non-null  float64
 20  Cost_of_Goods_Sold    25000 non-null  float64
 21  Gross_Profit          25000 non-null  float64
 22  Returns_Units         25000 non-null  int64
 23  Net_Revenue           25000 non-null  float64
dtypes: float64(8), int64(2), object(14)
memory usage: 4.6+ MB

In [14]:
dfV2.head(7)

,Date,Country,Region,City,Latitude,Longitude,Product_Category,Product_Sub_Category,Product_Name,Product_ID,...,Sales_Representative,Promotion,Sales_Revenue,Quantity_Sold,Unit_Price,Discount_Amount,Cost_of_Goods_Sold,Gross_Profit,Returns_Units,Net_Revenue
0,2019-01-01 00:25:38,Canada,Quebec,Montreal,45.5017,-73.5673,Accessories,Helmets,Sport-100 Helmet Red,HL-U509-R,...,Sarah Jenkins,WINTER_OFFER,240.33,7,34.33,34.0,153.87,52.46,0,206.33
1,2019-01-01 02:47:24,Pakistan,ICT,Islamabad,33.6844,73.0479,Accessories,Tires,Patch Kit/8 Patches,TI-R092,...,Ahmed Khan,NO_PROMO,31126.20,39,5.32,0.0,19258.25,11867.94,0,31126.20
2,2019-01-01 09:44:03,Pakistan,Sindh,Karachi,24.8607,67.0011,Components,Drivetrain,LL Crankset,CO-C11,...,Maria Garcia,EID_SPECIAL,276403.34,12,153.56,21906.1,190556.35,63940.90,0,254497.24
3,2019-01-01 11:04:04,Pakistan,Sindh,Karachi,24.8607,67.0011,Accessories,Helmets,Sport-100 Helmet Red,HL-U509-R,...,John Smith,NO_PROMO,40350.42,8,33.63,0.0,28083.81,12266.61,0,40350.42
4,2019-01-01 12:10:10,Germany,Berlin,Berlin,52.5200,13.4050,Accessories,Tires,Patch Kit/8 Patches,TI-R092,...,Fatima Ali,NO_PROMO,84.56,16,5.28,0.0,43.29,41.27,0,84.56
5,2019-01-01 14:56:43,Canada,Quebec,Montreal,45.5017,-73.5673,Bikes,Road Bikes,Road-650 Black,BK-R65B-52,...,John Smith,NO_PROMO,16263.17,4,4065.79,0.0,7136.17,9127.00,0,16263.17
6,2019-01-01 15:37:17,Pakistan,ICT,Islamabad,33.6844,73.0479,Clothing,Jerseys,Short-Sleeve Classic M,CL-J05-M,...,Sarah Jenkins,NO_PROMO,330835.87,49,45.01,0.0,191127.08,139708.79,0,330835.87

In [15]:
dfV2.tail(7)

,Date,Country,Region,City,Latitude,Longitude,Product_Category,Product_Sub_Category,Product_Name,Product_ID,...,Sales_Representative,Promotion,Sales_Revenue,Quantity_Sold,Unit_Price,Discount_Amount,Cost_of_Goods_Sold,Gross_Profit,Returns_Units,Net_Revenue
24993,2026-04-17 07:07:17,Canada,Ontario,Toronto,43.6532,-79.3832,Accessories,Helmets,Sport-100 Helmet Red,HL-U509-R,...,Fatima Ali,WINTER_OFFER,793.23,25,31.73,68.07,341.28,383.89,0,725.16
24994,2026-04-17 09:07:10,Pakistan,Punjab,Multan,30.1575,71.5249,Bikes,Mountain Bikes,Mountain-100 Black,BK-M18B-42,...,Wei Chen,NO_PROMO,2917086.25,8,2430.91,0.00,1365746.32,1551339.93,0,2917086.25
24995,2026-04-17 10:21:17,United Kingdom,England,London,51.5074,-0.1278,Clothing,Jerseys,Long-Sleeve Logo Jersey S,CL-J01-S,...,John Smith,NO_PROMO,419.98,9,46.66,0.00,232.42,187.57,0,419.98
24996,2026-04-17 19:26:39,India,Maharashtra,Mumbai,19.0760,72.8777,Bikes,Road Bikes,Road-150 Red,BK-R15R-62,...,Fatima Ali,NO_PROMO,9545.02,7,1363.57,0.00,6544.88,3000.14,0,9545.02
24997,2026-04-17 20:38:04,USA,New York,New York City,40.7128,-74.0060,Clothing,Jerseys,Short-Sleeve Classic M,CL-J05-M,...,Sarah Jenkins,EID_SPECIAL,2103.22,45,46.74,164.86,1255.81,682.54,0,1938.36
24998,2026-04-17 22:21:39,Pakistan,Sindh,Karachi,24.8607,67.0011,Accessories,Helmets,Sport-100 Helmet Black,HL-U509-B,...,Ahmed Khan,SUMMER25,137951.67,27,34.06,22874.81,83613.49,31463.37,0,115076.86
24999,2026-04-17 23:17:07,United Kingdom,England,London,51.5074,-0.1278,Components,Drivetrain,HL Mountain Pedal,CO-P22,...,Wei Chen,NO_PROMO,663.27,9,73.70,0.00,350.60,312.68,0,663.27